version: '3.8'

services:
  db:
    image: postgres:16.3
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Rasulbek
      POSTGRES_DB: test_db
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
    ports:
      - "3001:3001"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: Rasulbek
      DB_NAME: test_db
    depends_on:
      - db

volumes:
  db_data:
